### ISSUE TITLE
脚本

### ISSUE THREAD

**Issue by zol-c** [WindrunnerMax/SWVerifyCode#2]
可以做个油猴脚本（试图搞事）

**Comment by WindRunnerMax** [comment]
哈哈，主要是为了后端处理爬虫用的，油猴只能用js吧，js写验证码识别还没整过 \_(:△」∠)_

**Comment by WindRunnerMax** [comment]
兄弟，我写出来了，JavaScript下的那个就是油猴插件  
想法666

**Comment by idootop** [comment]
> 
> 
> 兄弟，我写出来了，JavaScript下的那个就是油猴插件
> 想法666

也可以直接把python上的cnn模型搬过来，用tensorflow.js推理
不过这种简单的验证码上cnn模型有点大材小用了hhh
JS代码学习了，666

**Comment by WindrunnerMax** [comment]
> > 兄弟，我写出来了，JavaScript下的那个就是油猴插件
> > 想法666
> 
> 也可以直接把python上的cnn模型搬过来，用tensorflow.js推理
> 不过这种简单的验证码上cnn模型有点大材小用了hhh
> JS代码学习了，666

哈哈，小插件而已，用tensorflow.js太大材小用了  
倒不如调用百度cdn了

**Comment by WindRunnerMax** [comment]
> > 兄弟，我写出来了，JavaScript下的那个就是油猴插件
> > 想法666
> 
> 也可以直接把python上的cnn模型搬过来，用tensorflow.js推理
> 不过这种简单的验证码上cnn模型有点大材小用了hhh
> JS代码学习了，666

哈哈，小插件而已，Tensorflow.js太大材小用了  
倒不如调用百度ocr了
